### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by troke12** [osu-datenshi/lets#1]
- [x] Ada bbrp beatmap yang belum bisa disubmit scorenya
- [x] Score relax perlu di recalculate
- [x] Ada beatmap yg pp mania nya gk keluar
